USE bulletin_board;

CREATE TABLE users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL ,
  PASS VARCHAR(100) NOT NULL
  );

CREATE TABLE tweets (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  TEXT TEXT,
  POST_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  );